import 'package:m_335_flutter/enums/user_motivation_enum.dart';
import 'package:m_335_flutter/models/user_model.dart';

List<UserModel> userData = [
  UserModel(
    username: "user1",
    email: "user1@mail.com",
    password: "hallo",
    name: "Luca Steiner",
    age: DateTime(2007, 3, 14),
    friends: [],
    aboutMe: "Love running in the mountains and staying active outdoors.",
    userMotivation: UserMotivation.running,
    creationTime: DateTime.now().subtract(const Duration(days: 250)),
  ),
  UserModel(
    username: "user2",
    email: "user2@mail.com",
    password: "hallo",
    name: "Noah Keller",
    age: DateTime(2006, 11, 4),
    friends: [],
    aboutMe: "Gym rat and future fitness coach.",
    userMotivation: UserMotivation.gym,
    creationTime: DateTime.now().subtract(const Duration(days: 180)),
  ),
  UserModel(
    username: "user3",
    email: "user3@mail.com",
    password: "hallo",
    name: "Mia Baumann",
    age: DateTime(2008, 7, 22),
    friends: [],
    aboutMe: "Enjoys hiking, yoga, and spending time with friends.",
    userMotivation: UserMotivation.yoga,
    creationTime: DateTime.now().subtract(const Duration(days: 320)),
  ),
  UserModel(
    username: "DummyUser",
    email: "dummy@user.com",
    password: "123456",
    name: "Raphaël Schreiber",
    age: DateTime(2008, 1, 25),
    friends: [],
    aboutMe: "Just testing BonApp — future CEO 😉",
    userMotivation: UserMotivation.other,
    creationTime: DateTime.now().subtract(const Duration(days: 60)),
  ),
  UserModel(
    username: "sofia98",
    email: "sofia98@mail.com",
    password: "securepass",
    name: "Sofia Meier",
    age: DateTime(2005, 9, 9),
    friends: [],
    aboutMe: "Loves swimming and late-night cycling through the city.",
    userMotivation: UserMotivation.swimming,
    creationTime: DateTime.now().subtract(const Duration(days: 400)),
  ),
  UserModel(
    username: "timothyX",
    email: "timx@mail.com",
    password: "timpass",
    name: "Tim Berger",
    age: DateTime(2004, 12, 30),
    friends: [],
    aboutMe: "Tech nerd, gamer, and occasional runner.",
    userMotivation: UserMotivation.running,
    creationTime: DateTime.now().subtract(const Duration(days: 95)),
  ),
  UserModel(
    username: "lea.walks",
    email: "lea@mail.com",
    password: "leapass",
    name: "Lea Marti",
    age: DateTime(2007, 5, 10),
    friends: [],
    aboutMe: "Walking every day clears the mind.",
    userMotivation: UserMotivation.walking,
    creationTime: DateTime.now().subtract(const Duration(days: 512)),
  ),
  UserModel(
    username: "marco22",
    email: "marco22@mail.com",
    password: "marco22",
    name: "Marco Keller",
    age: DateTime(2006, 2, 2),
    friends: [],
    aboutMe: "Climber and adventure enthusiast.",
    userMotivation: UserMotivation.climbing,
    creationTime: DateTime.now().subtract(const Duration(days: 220)),
  ),
  UserModel(
    username: "zoe_yoga",
    email: "zoe_yoga@mail.com",
    password: "peaceful",
    name: "Zoé Blaser",
    age: DateTime(2005, 6, 16),
    friends: [],
    aboutMe: "Yoga is not just movement, it's stillness in motion.",
    userMotivation: UserMotivation.yoga,
    creationTime: DateTime.now().subtract(const Duration(days: 670)),
  ),
  UserModel(
    username: "jan_cyclist",
    email: "jan_cyclist@mail.com",
    password: "jan2025",
    name: "Jan Schmid",
    age: DateTime(2006, 10, 11),
    friends: [],
    aboutMe: "Cycling every morning before sunrise keeps me grounded.",
    userMotivation: UserMotivation.cycling,
    creationTime: DateTime.now().subtract(const Duration(days: 150)),
  ),
];
